
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR DOT LPAREN OR PLUS QMARK RPAREN STARexpr2 : exprexpr : expr OR concatexpr : concatconcat : concat unaryconcat : unaryunary : atomic STAR\n             | atomic PLUS\n             | atomic QMARKunary : atomicatomic : DOTatomic : CHARatomic : LPAREN expr RPAREN'
    
_lr_action_items = {'DOT':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,],[6,6,-5,-9,-10,-11,6,6,-4,-6,-7,-8,6,-12,]),'CHAR':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,],[7,7,-5,-9,-10,-11,7,7,-4,-6,-7,-8,7,-12,]),'LPAREN':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,],[8,8,-5,-9,-10,-11,8,8,-4,-6,-7,-8,8,-12,]),'$end':([1,2,3,4,5,6,7,10,11,12,13,15,16,],[0,-1,-3,-5,-9,-10,-11,-4,-6,-7,-8,-2,-12,]),'OR':([2,3,4,5,6,7,10,11,12,13,14,15,16,],[9,-3,-5,-9,-10,-11,-4,-6,-7,-8,9,-2,-12,]),'RPAREN':([3,4,5,6,7,10,11,12,13,14,15,16,],[-3,-5,-9,-10,-11,-4,-6,-7,-8,16,-2,-12,]),'STAR':([5,6,7,16,],[11,-10,-11,-12,]),'PLUS':([5,6,7,16,],[12,-10,-11,-12,]),'QMARK':([5,6,7,16,],[13,-10,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr2':([0,],[1,]),'expr':([0,8,],[2,14,]),'concat':([0,8,9,],[3,3,15,]),'unary':([0,3,8,9,15,],[4,10,4,4,10,]),'atomic':([0,3,8,9,15,],[5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr2","S'",1,None,None,None),
  ('expr2 -> expr','expr2',1,'p_start','grep.py',46),
  ('expr -> expr OR concat','expr',3,'p_expression_or','grep.py',51),
  ('expr -> concat','expr',1,'p_expresssion_concat','grep.py',55),
  ('concat -> concat unary','concat',2,'p_concat','grep.py',59),
  ('concat -> unary','concat',1,'p_concat_unary','grep.py',63),
  ('unary -> atomic STAR','unary',2,'p_unary','grep.py',67),
  ('unary -> atomic PLUS','unary',2,'p_unary','grep.py',68),
  ('unary -> atomic QMARK','unary',2,'p_unary','grep.py',69),
  ('unary -> atomic','unary',1,'p_unary_atomic','grep.py',76),
  ('atomic -> DOT','atomic',1,'p_atomic_dot','grep.py',80),
  ('atomic -> CHAR','atomic',1,'p_atomic_char','grep.py',84),
  ('atomic -> LPAREN expr RPAREN','atomic',3,'p_atomic_exp_paren','grep.py',88),
]
